[package]
edition = "2021"
name = "zkaleido-risc0-artifacts"
version = "0.1.0"

[dependencies]

[build-dependencies]
risc0-build = "1.1.2"

[package.metadata.risc0]
methods = [
  "fibonacci",
  "sha2-chain",
  "schnorr-sig-verify",
  "fibonacci-composition",
]
