wrap_comments = true
binop_separator = "Front"
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
comment_width = 100
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
