use crate::{input::ZkVmInputBuilder, PerformanceReport, ZkVmProver, ZkVmVerifier};

/// A trait implemented by the prover ("host") of a zkVM program.
pub trait ZkVmHost: ZkVmProver + ZkVmVerifier {}

/// Extends the [`ZkVmHost`] trait by providing functionality to generate performance reports.
///
/// This trait introduces an additional method, `perf_report`, which accepts an input
/// constructed by the associated [`ZkVmInputBuilder`] and returns a [`PerformanceReport`].
pub trait ZkVmHostPerf: ZkVmHost {
    /// Produces a performance report based on the provided input.
    ///
    /// # Parameters
    /// - `input`: The input generated by a type implementing [`ZkVmInputBuilder`].
    ///
    /// # Returns
    /// A [`PerformanceReport`] containing metrics and other performance-related data
    /// gathered from the execution of the zero-knowledge VM.
    fn perf_report<'a>(
        &self,
        input: <Self::Input<'a> as ZkVmInputBuilder<'a>>::Input,
    ) -> PerformanceReport;
}
