[package]
name = "sha2-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
strata-zkvm = { path = "../../crates/zkvm" }
strata-native-zkvm-adapter = { path = "../../crates/native" }
sha2 = "0.10"
