[package]
name = "strata-sp1-artifacts"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20.2"

[build-dependencies]
sp1-helper = "3.3.0"
sp1-sdk = "3.3.0"
sha2 = "0.10"
bincode = "1.3"

[features]
mock = []
