use bn::{AffineG1, Fr, G1};
use sha2::{Digest, Sha256};
use zkaleido::{ProofReceipt, ZkVmError, ZkVmResult, ZkVmVerifier};

use crate::{
    error::{BufferLengthError, Groth16Error, InvalidProofFormatError, SerializationError},
    hashes::{blake3_to_fr, sha256_to_fr},
    types::{
        constant::{GROTH16_PROOF_COMPRESSED_SIZE, GROTH16_PROOF_UNCOMPRESSED_SIZE},
        proof::Groth16Proof,
        vk::Groth16VerifyingKey,
    },
    verification::verify_sp1_groth16_algebraic,
};

/// Number of bytes used from the SHA-256 hash of the Groth16 verifying key.
/// SP1 prepends these bytes to each raw Groth16 proof to ensure the proof
/// was generated with the expected verifying key.
pub const VK_HASH_PREFIX_LENGTH: usize = 4;

/// Number of 32-byte public-input fields embedded in SP1 6.1.0 Groth16 proofs:
/// exit code, recursion verifying-key root, and proof nonce.
const SP1_V6_PROOF_METADATA_LENGTH: usize = 32 * 3;

/// Successful SP1 execution is encoded as a zero field element.
const SUCCESS_EXIT_CODE: [u8; 32] = [0u8; 32];

/// A verifier for Groth16 proofs generated by SP1.
///
/// This verifier is agnostic to the specific SP1 version, as long as the
/// proving/verifying interface remains consistent. It checks that:
/// 1. The proof was generated with the expected Groth16 verifying key (by comparing the first
///    `VK_HASH_PREFIX_LENGTH` bytes of the key's SHA-256 hash).
/// 2. The Groth16 proof is valid with respect to two public inputs:
///    - `program_vk_hash`: a unique identifier for the SP1 program (as an Fr element).
///    - a hash of the supplied public values (either SHA-256 or Blake3).
#[derive(Clone, Debug)]
pub struct SP1Groth16Verifier {
    /// The (uncompressed) Groth16 verifying key for the SP1 circuit.
    pub vk: Groth16VerifyingKey,
    /// First `VK_HASH_PREFIX_LENGTH` bytes of `Sha256(groth16_vk)`, used to confirm
    /// the proof was generated with the correct key.
    pub vk_hash_tag: [u8; 4],
    /// SP1 recursion verifier-key root expected in SP1 v6 proof envelopes.
    pub vk_root: [u8; 32],
}

impl SP1Groth16Verifier {
    /// Loads a new `SP1Groth16Verifier` from a gnark compressed Groth16 verifying key and a
    /// program ID. This directly bakes fixed SP1 public inputs into the G1-key vector so that
    /// downstream callers only pass statement-specific inputs. For SP1 6.1.0, `program_vk_hash`
    /// and `vk_root` are fixed by the verifier instance, so the remaining inputs are
    /// `hash(public_values)`, `exit_code`, and `proof_nonce`.
    ///
    /// # Parameters
    /// - `vk_bytes`: Byte slice containing the gnark compressed Groth16 verifying key. Typically,
    ///   this is the [`static@sp1_verifier::GROTH16_VK_BYTES`] constant for the given SP1 version.
    /// - `program_id`: A 32-byte array representing the Fr-element identifier for the SP1 program.
    ///
    /// # Returns
    /// - `Ok(SP1Groth16Verifier)`: If the verifying key and program ID are successfully parsed.
    /// - `Err(Error)`: If `vk_bytes` is invalid or cannot be parsed into a verifying key.
    pub fn load(vk_bytes: &[u8], program_vk_hash: [u8; 32]) -> Result<Self, Groth16Error> {
        // Compute the SHA-256 hash of `vk_bytes` and take the first `VK_HASH_PREFIX_LENGTH` bytes.
        // This prefix is prepended to every raw Groth16 proof by SP1 to signal which verifying key
        // was used during proving.
        let digest = Sha256::digest(vk_bytes);
        let mut vk_hash_tag = [0u8; VK_HASH_PREFIX_LENGTH];
        vk_hash_tag.copy_from_slice(&digest[..VK_HASH_PREFIX_LENGTH]);
        let vk_root = *sp1_verifier::VK_ROOT_BYTES;

        // Parse the Groth16 verifying key from its byte representation.
        // This returns a `Groth16VerifyingKey` that can be used for algebraic verification.
        let mut groth16_vk = Groth16VerifyingKey::from_gnark_bytes(vk_bytes)?;

        // Parse the program ID (Fr element) from its 32-byte big-endian encoding.
        let program_vk_hash = Fr::from_slice(&program_vk_hash).map_err(SerializationError::from)?;

        if groth16_vk.g1.k.len() < 2 {
            return Err(Groth16Error::Serialization(
                BufferLengthError {
                    context: "Groth16 VK K points",
                    expected: 2,
                    actual: groth16_vk.g1.k.len(),
                }
                .into(),
            ));
        }

        // Fold the fixed program verification key hash into K0.
        let mut k0: G1 = groth16_vk.g1.k[0].into();
        let k1: G1 = groth16_vk.g1.k[1].into();
        k0 = k0 + (k1 * program_vk_hash);

        // SP1 6.1.0 adds vk_root as public input 3, corresponding to original K4. The verifier
        // already pins the SP1 verifier key root to this crate's sp1-verifier version, so fold it
        // into K0 as well and remove original K4 from the dynamic input basis.
        let merge_vk_root = groth16_vk.g1.k.len() >= 6;
        if merge_vk_root {
            let vk_root = Fr::from_slice(&vk_root).map_err(SerializationError::from)?;
            let k4: G1 = groth16_vk.g1.k[4].into();
            k0 = k0 + (k4 * vk_root);
        }

        let mut k = Vec::with_capacity(if merge_vk_root {
            groth16_vk.g1.k.len() - 2
        } else {
            groth16_vk.g1.k.len() - 1
        });
        k.push(AffineG1::from_jacobian(k0).unwrap().into());
        if merge_vk_root {
            k.extend_from_slice(&groth16_vk.g1.k[2..4]);
            k.extend_from_slice(&groth16_vk.g1.k[5..]);
        } else {
            k.extend_from_slice(&groth16_vk.g1.k[2..]);
        }
        groth16_vk.g1.k = k;

        Ok(SP1Groth16Verifier {
            vk: groth16_vk,
            vk_hash_tag,
            vk_root,
        })
    }

    /// Verifies a Groth16 proof against the given public values.
    ///
    /// The proof is expected to be encoded as:
    /// [ vk_hash_prefix (VK_HASH_PREFIX_LENGTH bytes) || raw_groth16_proof_bytes ]
    ///
    /// SP1 6.1.0 proofs instead include three public-input fields between the prefix and raw proof:
    ///
    /// [ vk_hash_prefix || exit_code || vk_root || proof_nonce || raw_groth16_proof_bytes ]
    ///
    /// The raw proof bytes can be in either compressed ([`GROTH16_PROOF_COMPRESSED_SIZE`] bytes) or
    /// uncompressed ([`GROTH16_PROOF_UNCOMPRESSED_SIZE`] bytes) format. The verifier automatically
    /// detects both the SP1 proof envelope and the raw proof format based on byte length.
    ///
    /// # Parameters
    /// - `proof`: Byte slice containing the prefixed Groth16 proof.
    /// - `public_values`: Byte slice representing the public values for the SP1 circuit.
    ///
    /// HACK: Because the proof format currently does not encode which hash function (SHA-256 vs.
    /// Blake3) was used to compute the public-values hash, we attempt verification with both:
    /// first using SHA-256, and if that fails, retrying with Blake3. In future versions, this
    /// could be improved by embedding a hash-selector byte in the proof to avoid redundant checks.
    pub fn verify(&self, proof: &[u8], public_values: &[u8]) -> Result<(), Groth16Error> {
        self.verify_with_exit_code(proof, public_values, SUCCESS_EXIT_CODE)
    }

    /// Verifies a Groth16 proof against the given public values and expected SP1 exit code.
    ///
    /// This is primarily useful for programs that intentionally panic. Most callers should use
    /// [`Self::verify`], which expects successful execution.
    pub fn verify_with_exit_code(
        &self,
        proof: &[u8],
        public_values: &[u8],
        expected_exit_code: [u8; 32],
    ) -> Result<(), Groth16Error> {
        // Ensure the proof is at least as long as the hash prefix.
        if proof.len() < VK_HASH_PREFIX_LENGTH {
            return Err(Groth16Error::Serialization(
                BufferLengthError {
                    context: "Groth16 proof with verifying key hash prefix",
                    expected: VK_HASH_PREFIX_LENGTH,
                    actual: proof.len(),
                }
                .into(),
            ));
        }

        // Compare the leading bytes of `proof` with our cached verifying-key hash. If they differ,
        // the proof was not generated with this verifying key.
        if self.vk_hash_tag != proof[..VK_HASH_PREFIX_LENGTH] {
            return Err(Groth16Error::VkeyHashMismatch);
        }

        // Extract the raw Groth16 proof (bytes after the prefix) and parse it.
        // Support SP1 v6 proof metadata, plus both compressed and uncompressed proof formats.
        let (proof, extra_public_inputs) = parse_proof_and_public_inputs(
            &proof[VK_HASH_PREFIX_LENGTH..],
            expected_exit_code,
            &self.vk_root,
        )?;

        // Compute Fr element for hash(public_values) using SHA-256. SP1's Groth16 circuit expects
        // a program vkey hash, hash(public_values), and SP1-version-specific metadata. Since SP1
        // allows either SHA-256 or Blake3 for the public values hash, we try SHA-256 first.
        let fr_sha2 = sha256_to_fr(public_values)?;
        let mut public_inputs = Vec::with_capacity(1 + extra_public_inputs.len());
        public_inputs.push(fr_sha2);
        public_inputs.extend_from_slice(&extra_public_inputs);

        // Attempt algebraic verification with SHA-256 hash as the second input.
        if verify_sp1_groth16_algebraic(&self.vk, &proof, &public_inputs).is_ok() {
            return Ok(());
        }

        // If SHA-256 verification fails, compute the Blake3 hash of `public_values` instead.
        let fr_blake3 = blake3_to_fr(public_values)?;
        public_inputs[0] = fr_blake3;

        // Retry algebraic verification using Blake3 hash as the second input.
        verify_sp1_groth16_algebraic(&self.vk, &proof, &public_inputs)
    }
}

fn parse_proof_and_public_inputs(
    proof_without_vk_hash: &[u8],
    expected_exit_code: [u8; 32],
    expected_vk_root: &[u8; 32],
) -> Result<(Groth16Proof, Vec<Fr>), Groth16Error> {
    match proof_without_vk_hash.len() {
        GROTH16_PROOF_COMPRESSED_SIZE => Ok((
            Groth16Proof::from_gnark_compressed_bytes(proof_without_vk_hash)?,
            Vec::new(),
        )),
        GROTH16_PROOF_UNCOMPRESSED_SIZE => Ok((
            Groth16Proof::from_uncompressed_bytes(proof_without_vk_hash)?,
            Vec::new(),
        )),
        len if len == SP1_V6_PROOF_METADATA_LENGTH + GROTH16_PROOF_COMPRESSED_SIZE => {
            let extra_public_inputs = parse_sp1_v6_public_inputs(
                proof_without_vk_hash,
                expected_exit_code,
                expected_vk_root,
            )?;
            let proof_bytes = &proof_without_vk_hash[SP1_V6_PROOF_METADATA_LENGTH..];
            Ok((
                Groth16Proof::from_gnark_compressed_bytes(proof_bytes)?,
                extra_public_inputs,
            ))
        }
        len if len == SP1_V6_PROOF_METADATA_LENGTH + GROTH16_PROOF_UNCOMPRESSED_SIZE => {
            let extra_public_inputs = parse_sp1_v6_public_inputs(
                proof_without_vk_hash,
                expected_exit_code,
                expected_vk_root,
            )?;
            let proof_bytes = &proof_without_vk_hash[SP1_V6_PROOF_METADATA_LENGTH..];
            Ok((
                Groth16Proof::from_uncompressed_bytes(proof_bytes)?,
                extra_public_inputs,
            ))
        }
        _ => Err(Groth16Error::Serialization(
            InvalidProofFormatError {
                expected_compressed: GROTH16_PROOF_COMPRESSED_SIZE,
                expected_uncompressed: GROTH16_PROOF_UNCOMPRESSED_SIZE,
                actual: proof_without_vk_hash.len(),
            }
            .into(),
        )),
    }
}

fn parse_sp1_v6_public_inputs(
    proof_without_vk_hash: &[u8],
    expected_exit_code: [u8; 32],
    expected_vk_root: &[u8; 32],
) -> Result<Vec<Fr>, Groth16Error> {
    let exit_code: [u8; 32] = proof_without_vk_hash[..32].try_into().map_err(|_| {
        Groth16Error::Serialization(SerializationError::from(BufferLengthError {
            context: "SP1 exit code",
            expected: 32,
            actual: proof_without_vk_hash.len(),
        }))
    })?;
    let vk_root: [u8; 32] = proof_without_vk_hash[32..64].try_into().map_err(|_| {
        Groth16Error::Serialization(SerializationError::from(BufferLengthError {
            context: "SP1 verifying key root",
            expected: 32,
            actual: proof_without_vk_hash.len().saturating_sub(32),
        }))
    })?;
    let proof_nonce: [u8; 32] = proof_without_vk_hash[64..96].try_into().map_err(|_| {
        Groth16Error::Serialization(SerializationError::from(BufferLengthError {
            context: "SP1 proof nonce",
            expected: 32,
            actual: proof_without_vk_hash.len().saturating_sub(64),
        }))
    })?;

    if exit_code != expected_exit_code {
        return Err(Groth16Error::ExitCodeMismatch);
    }

    if vk_root != *expected_vk_root {
        return Err(Groth16Error::VkeyRootMismatch);
    }

    [exit_code, proof_nonce]
        .iter()
        .map(|input| {
            Fr::from_slice(input)
                .map_err(SerializationError::from)
                .map_err(Into::into)
        })
        .collect()
}

impl ZkVmVerifier for SP1Groth16Verifier {
    fn verify(&self, receipt: &ProofReceipt) -> ZkVmResult<()> {
        self.verify(
            receipt.proof().as_bytes(),
            receipt.public_values().as_bytes(),
        )
        .map_err(|e| ZkVmError::ProofVerificationError(e.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use bn::{AffineG1, AffineG2, Fq, Fq2, G1, G2, Group};
    use rand::thread_rng;
    use sp1_verifier::GROTH16_VK_BYTES;
    use zkaleido::{ProofReceipt, ProofReceiptWithMetadata};

    use crate::{
        Groth16VerifyingKey, SP1_GROTH16_VK_COMPRESSED_SIZE_MERGED,
        SP1_GROTH16_VK_UNCOMPRESSED_SIZE_MERGED,
        error::Groth16Error,
        types::{
            constant::{GROTH16_PROOF_COMPRESSED_SIZE, GROTH16_PROOF_UNCOMPRESSED_SIZE},
            proof::Groth16Proof,
        },
        verifier::{SP1Groth16Verifier, VK_HASH_PREFIX_LENGTH},
    };

    const SP1_V5_GROTH16_VK_BYTES: &[u8] =
        include_bytes!("../../../../examples/groth16-verify-sp1/vk/sp1_groth16_vk.bin");

    fn load_verifier_and_proof() -> (SP1Groth16Verifier, ProofReceipt) {
        let receipt =
            ProofReceiptWithMetadata::load("./proofs/fibonacci_SP1_v5.0.0.proof.bin").unwrap();

        let verifier =
            SP1Groth16Verifier::load(SP1_V5_GROTH16_VK_BYTES, receipt.metadata().program_id().0)
                .unwrap();

        let receipt = receipt.receipt().clone();

        (verifier, receipt)
    }

    #[test]
    fn test_valid_proof() {
        let (verifier, receipt) = load_verifier_and_proof();
        let res = verifier.verify(
            receipt.proof().as_bytes(),
            receipt.public_values().as_bytes(),
        );
        assert!(res.is_ok());
    }

    #[test]
    fn test_invalid_g1() {
        let (mut verifier, receipt) = load_verifier_and_proof();
        let vk_alpha = verifier.vk.g1.alpha.0;
        let alpha_x = vk_alpha.x();
        let alpha_y = vk_alpha.y();

        let mut rng = thread_rng();
        let invalid_alpha_x = Fq::random(&mut rng);

        let res = AffineG1::new(alpha_x, alpha_y);
        assert!(res.is_ok());

        let res = AffineG1::new(invalid_alpha_x, alpha_y);
        assert!(res.is_err());

        let invalid_alpha =
            AffineG1::from_jacobian(G1::new(invalid_alpha_x, alpha_y, Fq::one())).unwrap();
        verifier.vk.g1.alpha.0 = invalid_alpha;

        let res = verifier.verify(
            receipt.proof().as_bytes(),
            receipt.public_values().as_bytes(),
        );
        assert!(res.is_err());

        let random_alpha = AffineG1::from_jacobian(G1::random(&mut rng)).unwrap();
        verifier.vk.g1.alpha.0 = random_alpha;
        let res = verifier.verify(
            receipt.proof().as_bytes(),
            receipt.public_values().as_bytes(),
        );
        assert!(res.is_err());
    }

    #[test]
    fn test_invalid_g2() {
        let (mut verifier, receipt) = load_verifier_and_proof();
        let vk_gamma = verifier.vk.g2.gamma.0;
        let gamma_x = vk_gamma.x();
        let gamma_y = vk_gamma.y();
        let invalid_gamma_x = gamma_x + Fq2::one();

        let res = AffineG2::new(gamma_x, gamma_y);
        assert!(res.is_ok());

        let res = AffineG2::new(invalid_gamma_x, gamma_y);
        assert!(res.is_err());

        let invalid_gamma =
            AffineG2::from_jacobian(G2::new(invalid_gamma_x, gamma_y, Fq2::one())).unwrap();
        verifier.vk.g2.gamma.0 = invalid_gamma;

        let res = verifier.verify(
            receipt.proof().as_bytes(),
            receipt.public_values().as_bytes(),
        );
        assert!(res.is_err());

        let mut rng = thread_rng();
        let random_gamma = AffineG2::from_jacobian(G2::random(&mut rng)).unwrap();
        verifier.vk.g2.gamma.0 = random_gamma;
        let res = verifier.verify(
            receipt.proof().as_bytes(),
            receipt.public_values().as_bytes(),
        );
        assert!(res.is_err());
    }

    #[test]
    fn test_compressed_and_uncompressed_proof() {
        let (verifier, receipt) = load_verifier_and_proof();
        let proof_bytes = receipt.proof().as_bytes();
        let public_values = receipt.public_values().as_bytes();

        // Extract raw proof (without VK hash prefix)
        let raw_proof_bytes = &proof_bytes[VK_HASH_PREFIX_LENGTH..];

        // Parse the proof
        let parsed_proof = Groth16Proof::from_uncompressed_bytes(raw_proof_bytes).unwrap();

        // Convert to compressed format
        let compressed = parsed_proof.to_gnark_compressed_bytes();
        assert_eq!(compressed.len(), GROTH16_PROOF_COMPRESSED_SIZE);

        // Convert to uncompressed format
        let uncompressed = parsed_proof.to_uncompressed_bytes();
        assert_eq!(uncompressed.len(), GROTH16_PROOF_UNCOMPRESSED_SIZE);

        // Create proof with VK hash prefix for compressed
        let mut compressed_proof_with_prefix = Vec::new();
        compressed_proof_with_prefix.extend_from_slice(&verifier.vk_hash_tag);
        compressed_proof_with_prefix.extend_from_slice(&compressed);

        // Create proof with VK hash prefix for uncompressed
        let mut uncompressed_proof_with_prefix = Vec::new();
        uncompressed_proof_with_prefix.extend_from_slice(&verifier.vk_hash_tag);
        uncompressed_proof_with_prefix.extend_from_slice(&uncompressed);

        // Verify both compressed and uncompressed proofs work
        let res_compressed = verifier.verify(&compressed_proof_with_prefix, public_values);
        assert!(
            res_compressed.is_ok(),
            "Compressed proof verification failed: {:?}",
            res_compressed
        );

        let res_uncompressed = verifier.verify(&uncompressed_proof_with_prefix, public_values);
        assert!(
            res_uncompressed.is_ok(),
            "Uncompressed proof verification failed: {:?}",
            res_uncompressed
        );
    }

    #[test]
    fn test_compressed_merged_vk_roundtrip() {
        let (verifier, _) = load_verifier_and_proof();

        let gnark_vk_bytes = verifier.vk.to_gnark_bytes();
        let vk = Groth16VerifyingKey::from_gnark_bytes(&gnark_vk_bytes).unwrap();
        assert_eq!(vk, verifier.vk);

        let uncompressed_vk_bytes = verifier.vk.to_uncompressed_bytes();
        let vk = Groth16VerifyingKey::from_uncompressed_bytes(&uncompressed_vk_bytes).unwrap();
        assert_eq!(vk, verifier.vk);
    }

    #[test]
    fn test_sp1_v6_vk_load_merges_public_inputs() {
        let verifier = SP1Groth16Verifier::load(&GROTH16_VK_BYTES, [0u8; 32]).unwrap();

        let gnark_vk_bytes = verifier.vk.to_gnark_bytes();
        assert_eq!(gnark_vk_bytes.len(), SP1_GROTH16_VK_COMPRESSED_SIZE_MERGED);
        let vk = Groth16VerifyingKey::from_gnark_bytes(&gnark_vk_bytes).unwrap();
        assert_eq!(vk, verifier.vk);

        let uncompressed_vk_bytes = verifier.vk.to_uncompressed_bytes();
        assert_eq!(
            uncompressed_vk_bytes.len(),
            SP1_GROTH16_VK_UNCOMPRESSED_SIZE_MERGED
        );
        let vk = Groth16VerifyingKey::from_uncompressed_bytes(&uncompressed_vk_bytes).unwrap();
        assert_eq!(vk, verifier.vk);
    }

    #[test]
    fn test_sp1_v6_proof_rejects_wrong_vk_root() {
        let verifier = SP1Groth16Verifier::load(&GROTH16_VK_BYTES, [0u8; 32]).unwrap();
        let mut proof = Vec::new();
        proof.extend_from_slice(&verifier.vk_hash_tag);
        proof.extend_from_slice(&[0u8; 32]);
        proof.extend_from_slice(&[1u8; 32]);
        proof.extend_from_slice(&[0u8; 32]);
        proof.extend_from_slice(&[0u8; GROTH16_PROOF_UNCOMPRESSED_SIZE]);

        let err = verifier.verify(&proof, &[]).unwrap_err();
        assert!(matches!(err, Groth16Error::VkeyRootMismatch));
    }
}
