[package]
name = "zkaleido-groth16-verifier"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
hex.workspace = true
bn = { version = "0.6.0", package = "substrate-bn" }
thiserror.workspace = true
