[package]
name = "composition"
version = "0.1.0"
edition = "2024"

[dependencies]
zkaleido = { path = "../../zkaleido", features = ["perf"] }
zkaleido-native-adapter = { path = "../../adapters/native" }
