[package]
edition = "2021"
name = "guest-sp1-fibonacci"
version = "0.1.0"

[workspace]

[dependencies]
fibonacci = { path = "../../../examples/fibonacci" }
zkaleido-sp1-adapter = { path = "../../../adapters/sp1", features = ["zkvm"] }
sp1-zkvm = "4.0.0"
