[package]
edition = "2021"
name = "zkaleido"
version = "0.1.0"

[dependencies]
arbitrary.workspace = true
bincode.workspace = true
borsh.workspace = true
serde.workspace = true
thiserror.workspace = true

[features]
default = ["perf"]
perf = []
