[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"

[dependencies]
strata-zkvm = { path = "../../zkvm", features = ["perf"] }
strata-native-zkvm-adapter = { path = "../../adapters/native" }
