[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"

[dependencies]
zkaleido = { path = "../../zkaleido", features = ["perf"] }
strata-native-zkvm-adapter = { path = "../../adapters/native" }
