[package]
edition = "2021"
name = "zkaleido-native-adapter"
version = "0.1.0"

[dependencies]
zkaleido.workspace = true

bincode.workspace = true
borsh.workspace = true
serde.workspace = true
tracing.workspace = true
