[package]
edition = "2021"
name = "strata-native-zkvm-adapter"
version = "0.1.0"

[dependencies]
strata-zkvm.workspace = true

bincode.workspace = true
borsh.workspace = true
serde.workspace = true
tracing.workspace = true
