name: Install toolchains
description: "Helper to install ZKVM toolchains."
inputs: {}
outputs: {}

runs:
  using: "composite"
  steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: Install SP1 Toolchain
      shell: bash
      run: |
        curl -fsSL --proto '=https' --tlsv1.2 https://sp1.succinct.xyz | bash && ~/.sp1/bin/sp1up
        export PATH=~/.sp1/bin:$PATH
        cargo prove --version

    - name: Install RISC0 Toolchain
      shell: bash
      run: |
        curl -fsSL --proto '=https' --tlsv1.2 https://risczero.com/install | bash && ~/.risc0/bin/rzup install
        export PATH=~/.risc0/bin:$PATH
        rzup check
